CREATE DATABASE PIZZA

USE PIZZA

SELECT * FROM [dbo].[pizza]


--What is the total revenue of the pizza company?
SELECT CAST(SUM(TOTAL_PRICE) AS DECIMAL (10,2)) AS 'TOTAL REVENUE' FROM [dbo].[pizza]


--What is the average order value of the pizza company?

SELECT ROUND(SUM(TOTAL_PRICE), 2) AS 'TOTAL REVENUE', COUNT(DISTINCT(ORDER_ID)) AS 'TOTAL ORDERS', ROUND(SUM(TOTAL_PRICE)/COUNT(DISTINCT(ORDER_ID)), 2) AS 'AVG_ORDER_VALUE'
FROM [dbo].[pizza]


--How many pizzas and orders did the pizza company sell?
SELECT * FROM [dbo].[pizza]

SELECT COUNT(QUANTITY) AS 'TOTAL PIZZA SOLD' , COUNT(DISTINCT(ORDER_ID)) AS 'TOTAL ORDERS'
FROM [dbo].[pizza]


-- What is the average number of pizzas sold per order?

SELECT * FROM [dbo].[pizza]

SELECT ROUND((SUM(QUANTITY)) / COUNT(DISTINCT(ORDER_ID)), 2) AS 'AVG-PIZZA-PER-ORDER'
FROM [dbo].[pizza]


-- DAILY TREND FOR TOTAL ORDERS

SELECT * FROM [dbo].[pizza]

SELECT DATENAME(WEEKDAY, ORDER_DATE) AS 'ORDER DAY',
COUNT(DISTINCT(ORDER_ID)) AS 'TOTAL ORDER'
FROM [dbo].[pizza]
GROUP BY DATENAME(WEEKDAY, ORDER_DATE)
ORDER BY COUNT(DISTINCT(ORDER_ID)) DESC


-- MONTHLY TREND

SELECT DATENAME(MONTH, ORDER_DATE) AS 'ORDER DAY',
COUNT(DISTINCT(ORDER_ID)) AS 'TOTAL ORDER'
FROM [dbo].[pizza]
GROUP BY DATENAME(MONTH, ORDER_DATE)
ORDER BY COUNT(DISTINCT(ORDER_ID)) DESC;

--PERCENTAGE OF SALES BY PIZZA CATEGORY

SELECT * FROM [dbo].[pizza]

SELECT PIZZA_CATEGORY, PIZZA_SIZE, COUNT(*) AS 'TOTAL', ROUND(SUM(TOTAL_PRICE), 2) AS 'REVENUE', ROUND(SUM(total_price)* 100 / (SELECT SUM(TOTAL_PRICE) FROM [dbo].[pizza]) ,0) AS 'PIZZA_SALES_CATEGORY_WISE'
FROM [dbo].[pizza]
GROUP BY PIZZA_CATEGORY, PIZZA_SIZE
ORDER BY PIZZA_CATEGORY DESC

--PERCENTAGE OF SALES BY PIZZA SIZE

SELECT PIZZA_SIZE, ROUND(SUM(TOTAL_PRICE) * 100 / (SELECT SUM(TOTAL_PRICE) FROM [dbo].[pizza]) ,0) AS 'PST'
FROM [dbo].[pizza]
GROUP BY PIZZA_SIZE
ORDER BY PST;

SELECT * FROM[dbo].[pizza]

-- TOP 5 PIZZA BY QUANTITY

SELECT TOP 5 PIZZA_NAME_ID, ROUND(SUM(QUANTITY),2) AS 'TOTAL QUANTITY'
FROM [dbo].[pizza]
GROUP BY PIZZA_NAME_ID
ORDER BY SUM(QUANTITY) DESC;

-- BOTTOM 5 PIZZA BY QUANTITY

SELECT TOP 5 PIZZA_NAME_ID, ROUND(SUM(QUANTITY),2) AS 'TOTAL QUANTITY'
FROM [dbo].[pizza]
GROUP BY PIZZA_NAME_ID
ORDER BY SUM(QUANTITY) ASC;


-- TOP 5 PIZZA BY REVENUE

SELECT TOP 5 PIZZA_NAME_ID, ROUND(SUM(TOTAL_PRICE),2) AS 'TOTAL REVENUE'
FROM [dbo].[pizza]
GROUP BY PIZZA_NAME_ID
ORDER BY SUM(TOTAL_PRICE) DESC;



